name: Auto Accept Collabs

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0/5 * * * *
  issues:
    types: [opened]

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@latest
      - name: Auto Accept Collabs
        uses: kbrashears5/github-action-auto-accept-collabs@v2.0.0
        with:
          TOKEN: ${{ secrets.ACTIONS }}
